### ISSUE TITLE
Settings.json -problems

### ISSUE THREAD

**Issue by zackmuc** [Steccas/xbs-api-docker#2]
I added:

"maxSyncSize": 4096000

but somehow i still have only 500 kb shown in the client.

![image](https://user-images.githubusercontent.com/4520343/170886178-c50105b4-9ff1-4d58-8410-ba4f101c0394.png)

**Comment by jaquer** [comment]
I can't reproduce this. Your `settings.json` file should look like this:

    {
      "db": {
        "host": "db"
      },
      "maxSyncSize": 4096000
    }

Notice the comma after the `"host": "db"` closing bracket. Forgetting to add it will make your JSON invalid.

If you're still having trouble post your entire `settings.json` and `docker-compose.yml` files.

**Comment by zackmuc** [comment]
Oh found it had a typo .. thx could be closed.
